os:
  - linux
  - osx
language: node_js
node_js:
  - '7'
  - '8'
  - '9'
script: "npm test"
env:
  global:
  - secure: Q40uAyIda8L4FbiOA6bH4pmkcRMvTNT3JiSHOFXqnWPn9ZTdnXfpCmH8xLZ9ac9DshGaq0PAP1jUsbnXgiR+MiHuVnoKXaY+KxqdJL+xBL2t594MMTzPHc6RyxtUMVQHPXAvqJFJPQ8yGc0SI/GTaqx+7apNfOcdz9SrQ6oPn3E159H+LzuJtxg1rBC1ihinJC8bfuxRCC3yziVhSaeEN7cHMNtzN4TGaoZDJi8zwMbw3M8BL82qpS4Fm5LV20vAyyAOf9l+xxdplMMf0H1B7aAeCrcflwGFBIpYN1AgE+TlltpTN8FRwlYsJGTfmd8jcY3dHtJHF60c8x/qDxsfBvBmxFgc1GfgqzcP+UPp73Mq7g6cgotgV5c/Rgt/ekIsC5+kcQO0Sl09UrWPWRrspd7qD7NSq/sihND/9WRl2+U9HHcmPH6q8MDFBGDhtenUTlsSl+J932tkS85amugDDJRYwHxsOxrNnfwaeKPtoLtloNCqBjb6zJ37ZrzU2/yuo2+D++jY2pe+sYMCnomFZSvDq9LE5nin71jpvj5+y3ojW2GiOoG7CgxfgW2gFZRj008X04XA/DmodQ3tMCkXKR6Winm5+rNZdH1F5GzY4bK0LDAM+X4F06BKXqJQ/LFd0c49qncF2d4FR8JjikaNUWLLfLDs6zl0JSNELqu8qaU=
  - secure: cQVO+mNCkzc8dX8tPZ6FnfafVAIJ84o+NBgXiZeDsX+kybAeECLWU6PhzWsCtrNOWL+zzIqsJqyVQU38XWNRg0R3NACz7pSd/u2ulcDD4lSZaIMxFb9YJOOQIx3zma9rnh7WmXV2EIFLu/uTCZsGcuP2as80QF0YWCPg1gcNWxSV8QDG4MjxgJ22WXXyVVqg9qubWQoXOGXNOgnJSCPLKEDdQcXCKmZsT8b+VgzzmFdyptCwbECCEd+ibk9aI3VFve6Jef/bu1Fo1M9JQRBQ8TSR8oAOWRRgWF2VyZ5B7gYXR/3MvQ3Xsmq77D2QnU468SW3kYLdlu19EPObr5o7LnoksT24GrGaHW8OkcIkTSh1pXFLpQxc61y9+tJ7yIKiCjSHXcNyL9u6FxWGp5FAvWBLyymQ7uTbvOEvPvEgYfEG0AvqzCi5GeMcDEjuSPO1gbH75OMRdaDfH0CoLzRx4Wj9oszxY+xR9Ma+kb5XUpiGRkASic0yhccX8tfJktGf8P+AfipBNBh+O21SKwPZFmfbhPEyrJVTnR/goR07Iu3E6NajhwOUdmQJCU4at9C20v20eQZE+jiitjUmk8S6MsIwQmXCG12wit8/F8mil4UOgqlS4Fvq+U1XYwRpJv8NHAl2OJm2gzmHWvdKiDLY5THWAdP01S8c2Y4vZrpjjBs=
