#%RAML 1.0 Trait

responses:
  '406':
    description: Content-Type e Accept mancanti o errati.
  '409':
    description: Conflitto.
  '500':
    description: Errore interno.
  '401':
    description: Autorizzazione negata.
  '403':
    description: Utente non autorizzato ad accedere alla risorsa.
  '404':
    description: URL errato.
  '429':
    description: Troppe richieste.
  '503':
    description: Risorsa temporaneamente non disponibile.